apiVersion: podinfo.interview.assignment/v1alpha1
kind: MyAppResource
metadata:
  name: example-myappresource
spec:
  replicaCount: 2
  resources:
    memoryLimit: 64Mi
    cpuRequest: 100m
  image:
    repository: ghcr.io/stefanprodan/podinfo
    tag: latest
  ui:
    color: "#34577c"
    message: "Hi!"
  redis:
    enabled: true
    server:
  env:
    - name: PODINFO_CACHE_SERVER
      value: tcp://redis:6379
