apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myappresources.podinfo.interview.assignment
spec:
  group: podinfo.interview.assignment
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicaCount:
                  type: integer
                resources:
                  type: object
                  properties:
                    memoryLimit:
                      type: string
                    cpuRequest:
                      type: string
                image:
                  type: object
                  properties:
                    repository:
                      type: string
                    tag:
                      type: string
                ui:
                  type: object
                  properties:
                    color:
                      type: string
                    message:
                      type: string
                redis:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    server:
                      type: string
                env:  
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
  scope: Namespaced
  names:
    plural: myappresources
    singular: myappresource
    kind: MyAppResource
